name: CD / Publish release
on:
  release:
    types: [published]

jobs:
  deploy:
    name: Publish release
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test

    steps:
      - name: Display build environment
        run: printenv
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set version in readme
        uses: weareyipyip/set-version-action@v2
        id: set-version
        with:
          source: tag
          file_path: README.md
      - name: Set version in mix.exs
        uses: weareyipyip/set-version-action@v2
        id: set-version
        with:
          source: tag
          file_path: mix.exs

      - uses: erlef/setup-beam@v1
        with:
          otp-version: 22.x
          elixir-version: 1.10.x
      - name: Install dependencies
        run: mix do local.hex --force, local.rebar --force, deps.get

      - name: Compile code (warnings as errors)
        run: mix compile --warnings-as-errors
      - name: Check code formatting
        run: mix format --check-formatted
      - name: Run tests (with coverage)
        run: mix test --cover
      - name: Create docs
        run: mix docs
      - name: Publish release
        run: mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
