name: CI / Automated testing
on:
  push:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Elixir ${{matrix.elixir}}
    env:
      MIX_ENV: test

    strategy:
      matrix:
        elixir: [1.10.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 22.x
          elixir-version: ${{matrix.elixir}}
      - name: Cache deps
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: deps-v2-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-v2-${{ matrix.elixir }}-
      - name: Display build environment
        run: printenv
      - name: Install dependencies
        run: mix do local.hex --force, local.rebar --force, deps.get
      - name: Check code formatting
        run: mix format --check-formatted
      - name: Compile code (warnings as errors)
        run: mix compile --warnings-as-errors
      - name: Run tests (with coverage)
        run: mix test --cover
      - name: Create docs
        run: mix docs
      - name: Run dialyzer
        run: mix dialyzer
